- trusted-committer-article.md
- trusted-committer-script.md
This PR is the result of a quick once-over, removes typos, grammar errors and in some cases streamlined the content and explanations.
> Small improvements to the article

- README.md
I missed this reference in the README file.
> Add the Chatham House Rule mention

- trusted-committer/outline.md
/CC @cewilliams , @rrrutledge, @_utanapishtim
> initial outline with Russ Rutledge and Cedric Williams and Noah Cawley

- contributor/outline.md
Added a number of points from the brain storm document, I'm welcoming discussion on them.
I also found a number of points that might be more relevant for the host side, I'll add them in a second document - we've merged&finished the TC now, however I figured I put them somewhere, maybe for a later text update.
> Add additional points from the brainstorm document.

- contributor/outline.md
* PR for the [Polished content outline](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/56) issue.
* View the [rendered markdown](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/contributor/outline/contributor/outline.md).
> Polished content outline

- contributor/outline.md
Looping in after-merge feedback from https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/59.  Thanks, @gruetter!
> Feedback for contributor/outline

- meetings/roles.md
* Feedback from 5/9 call.
* Also curious for review from @mtabbal
> Send out write-enabled link

- contributor/video-proposal.md
Filled out the Video Proposal Markdown document discussed in #49 borowing something from #47. 
Happy to see you comments and reviews :)
> Fill out the Contributor Video Proposal with a draft.

- README.md
Review the existing finished content
> How to get started

- meetings/roles.md
* Salient -> Key
* Easier for folks to understand and still communicates the same point.
> Adjusted language in role defintions

- README.md
- contributor/video-proposal.md
- introduction/01-introduction.md
- introduction/02-problems-solved.md
- introduction/03-how-works.md
- introduction/04-benefits.md
- introduction/06-conclusion.md
- introduction/outline.md
- introduction/principles.md
- trusted-committer/01-introduction.md
- trusted-committer/03-keeping-the-community-healthy.md
- trusted-committer/05-lowering-the-barriers-to-entry.md
- trusted-committer/07-becoming-a-trusted-committer.md
- trusted-committer/outline.md
- trusted-committer/trusted-committer-script.md
Almost all occurrences of "inner source" were already converted to "InnerSource"
> * Trivial fixing of typos etc

- contributor/outline.md
Taken from Open Source projects: There are some where people collaborate because they would not be able to build the equivalent system in-house - so they collaborate to share the cost of development (or expressed another way to grow beyond what they could accomplish alone.)
> Add the cost sharing aspect to company level benefits

- README.md
- meetings/roles.md
paypalflow -> innersourcecommons
> Fix Slack name

- contributor/01-introduction-article.md
* Responding to this [comment](https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/98/files#r312734706).
* Avoid explicitly bringing up contributions outside of repo contents.
> Rephrase contributor definition

- contributor/01-introduction-article.md
Suggestion to add to https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/98
> Heading suggestions

- contributor/01-introduction-article.md
To appeal to an individual who just cares about making progress on their project.
> Rewrite introductory paragraphs

- introduction/principles.md
Per previous discussions the review as pull request with some minor changes. (relates to https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/36)
> Some wordsmithing / review

- contributor/05-benefits-of-contribution.md
A first draft for the article on the benefits of Inner Source contributions.
Fixes #76 
A lot of the paragraphs in here are inspired by the outcome of a session on how to talk employers into giving people time to contribute to open source collected there: http://github.com/mainec/ribbit
I'm sure a few reasons are missing. Please feel free to point those out.
> Benefits of contribution

- contributor/01-introduction-script.md
- contributor/02-becoming-a-contributor-script.md
- contributor/03-contributor-ethos-script.md
- contributor/04-mechanics-of-contributing-script.md
- contributor/05-benefits-of-contribution-script.md
- contributor/06-conclusion-script.md
This PR adds a bunch of stubs for the video scripts with their duration and planned content from the Playbook.
> Add Contributor section stubs

- meetings/roles.md
We're on a regular schedule now.
> Time of next meeting not needed in the notes

- README.md
How to name and place articles, scripts, and workbooks.
> Updated file naming scheme

- contributor/06-conclusion.md
Adds initial version for the conclusion article. 
Happy to see reviews and extensions.
> Addresses #78 - adds conclusion article starter

- contributor/01-introduction-script.md
Here's an initial version of a script for the introduction video of the Contributor section.
Happy about any reviews and proposals to shorten the text.
> Fix #131 Add starter version of the Contributor Introduction Script

- introduction/01-introduction.md
- introduction/02-problems-solved.md
- introduction/03-how-works.md
- introduction/04-benefits.md
- introduction/05-principles.md
Included in the original pull request for context but no longer needed.
> Remove meta information

- contributor/05-benefits-of-contribution-script.md
Again this converts the slide speaker notes to a script.
> Add script for benefits of contribution section.

- contributor/04-mechanics-of-contributing-script.md
Here's a draft PR for the mechanics of contributing script.
I'll add more text later from the articles, this is for now just the recording of meeting notes with @MaineC and @lenucksi.
> Draft Mechanics script fix #137

- contributor/02-becoming-a-contributor-script.md
Essentially this translates the speaker notes of the slides for this section into a script.
> Add script for the becoming a contributor section.

- contributor/03-contributor-ethos-script.md
Much like #154 this is mostly based on the speaker notes that I already had in the slides for the videos.
> Add contributor ethos script based on articles.

- contributor/01-introduction-script.md
This assigns paragraphs to speakers. Please check that this works for you.
> Assigns paragraphs to speakers

- contributor/03-contributor-ethos-script.md
... this time for the contributor ethos part.
> Assign paragraphs to speakers

- contributor/01-introduction-script.md
(timed when speaking/ reading aloud)
> Shortened to fit into 3 mintues.

- contributor/04-mechanics-of-contributing-script.md
- Removed duplications compared to [03-ethos](contributor/03-contributor-ethos-script.md)
- Shortend internal duplications
- Shortened in general
> Shorten parts of the mechanics script to make it fit the time.

- contributor/01-introduction-script.md
- contributor/03-contributor-ethos-script.md
- contributor/05-benefits-of-contribution-script.md
Removed a few superfluous newlines and removed the last paragraph from the benefits script. 
Reading this before the conclusion script made it feel like it would be last video, which it isn't. 
Contentwise it's great and maybe some of it should be transferred to the conclusion video but that one already matches most points of that paragraph.
> Add some more cleanups + remove possibly duplicated content

- contributor/01-introduction-article.md
- contributor/02-becoming-a-contributor-article.md
- contributor/03-contributor-ethos-article.md
- contributor/04-mechanics-of-contributing-article.md
- contributor/05-benefits-of-contribution-article.md
- contributor/06-conclusion-article.md
- introduction/01-introduction.md
- introduction/02-problems-solved.md
- introduction/03-how-works.md
- introduction/04-benefits.md
- introduction/05-principles.md
- introduction/06-conclusion.md
- trusted-committer/01-introduction.md
- trusted-committer/02-ensuring-product-quality.md
- trusted-committer/03-keeping-the-community-healthy.md
- trusted-committer/04-uplevelling-community-members.md
- trusted-committer/05-lowering-the-barriers-to-entry.md
- trusted-committer/06-advocating-for-the-communitys-needs.md
- trusted-committer/07-becoming-a-trusted-committer.md
- trusted-committer/08-conclusion.md
Aligned article headers to O'Reilly standard (H1) 
[#114 ](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/114)
> addresses #114

- README.md
This concludes the work for #123 by adding the workbook to the README.md.
> Include the workbook in the README.md, last fix for #123

- contributor/03-contributor-ethos-article.md
Addresses #182 - changes to 03-contributor-ethos-article
> Ludmila n style 03 contributor ethos article

- contributor/06-conclusion-article.asciidoc
Minor grammar/style changes to contributor/06-conclusion-article.
> Style - conclusion article

- trusted-committer/03-keeping-the-community-healthy.asciidoc
> Sync 03-keeping-the-community-healthy from Atlas

- introduction/03-how-works.asciidoc
- introduction/de/03-how-works.asciidoc
- introduction/zh/03-InnerSource如何运作.asciidoc
Markdown link accidentally got renamed as ASCIIDOC
> Fix broken link

- config/urls.yaml
Do not merge until https://github.com/InnerSourceCommons/innersourcecommons.org/pull/159 is complete.
Fixes #207.
> Update isc urls to latest self-hosted locations.

- CONTRIBUTING.md
- README.md
Putting instructions and info from https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/219 into our docs.
> Translation instructions

- CONTRIBUTING.md
- README.md
* Update README to represent the shifting focus of the working group towards any learning segments on InnerSource (not just the original ones sponsored by PayPal).
* Update CONTRIBUTING with the overall flow of how to work with the community to bring a segment from idea to finished product.
> Revamp community documentation

- workbook/02-trusted-committer.asciidoc
Without the additional new line the header won't be displayed as such.
> Fix header formatting

- CONTRIBUTING.md
- outline-template.md
Template for creating an outline for segment.
> Create segment outline

- trusted-committer/de/04-uplevelling-community-members.asciidoc
after some longer summer break I finished the translation of chapter 04. :-). I am happy to see your review comments
> Addresses #256 translate trusted committer chapter04

- trusted-committer/de/05-lowering-the-barriers-to-entry.asciidoc
some meeting with only stand-by duty helped me to finish chapter05. :-)
> draft translation of chapter 05

- introduction/it/01-introduction.asciidoc
- introduction/it/02-problems-solved.asciidoc
- introduction/it/03-how-works.asciidoc
- introduction/it/04-benefits.asciidoc
- introduction/it/05-principles.asciidoc
- introduction/it/06-conclusion.asciidoc
This is just a first version of the italian translation.
> first commit of italian translation

- trusted-committer/de/08-conclusion.asciidoc
finally the last chapter of trusted committer translated.
> 256 translate trusted committer chapter08

- scripts/generate_learning_path_markdown.js
Generated files in pull request at https://github.com/InnerSourceCommons/innersourcecommons.org/pull/214
> Generate Italian Introduction articles

- scripts/README.md
View the [rendered markdown](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/docs/scripts/scripts/README.md).
> How to update innersourcecommons.org with new articles

- workbook/01-introduction.asciidoc
…t in Update 01-introduction.ascii.doc
> Correct display issues in introduction workbook

- CONTRIBUTING.md
@WilllemJiang and @marshmallowrobot please have a look.
> Explanation of how to add subtitles

- workbook/04-contributor.asciidoc
In the first segment, question 3 is actually question 2
> [Contributor] workbook updates

- trusted-committer/ja/02-ensuring-product-quality-ja.asciidoc
This is the second PR for #367 .
> Translation-ja: Add trusted-committer/ja/02-ensuring-product-quality

- contributor/de/01-introduction-article-de.asciidoc
Hi, I started translation again, here the translation of the first chapter of contributor
> German translation contributor chapter 01

- scripts/get_contributors.js
* When someone leaves a commit suggestion that is merged, they show up as a 'co-author' on that commit
* GitHub exposes this information in their graph API (https://bit.ly/3cdyYQQ)
* You can see the script output at https://github.com/InnerSourceCommons/innersourcecommons.org/pull/257
> List Co-Committers as Learning Path Contributors

- contributor/de/index.md
- introduction/de/index.md
- product-owner/de/index.md
- trusted-committer/de/index.md
Hi Tom, I created german translations of the md files as you suggested for each section. I put it into the ../de folder. 
In the introduction file you have a variable featured: true, I just kept that, even if not knowing what it means and why it is not in the other sections.
Please let me know if I have some misunderstanding.
@lenucksi maybe you would like to review the translation.
> #382 creation of german index.md files

- scripts/generate_learning_path_markdown.js
Generates placeholder text as per https://github.com/InnerSourceCommons/innersourcecommons.org/pull/97.
This PR needs to be merged before we next update the website, else the placeholder text will be lost.
> Generate placeholder text where index not translated

- contributor/de/02-becoming-a-contributor-article-de.asciidoc
Hi, I again found some time to translate another chapter of the contributor series into german, chapter 02. Letters are swirling around my eyes now and reading the 5th time will not change it anymore, so I will set this for review.
> #254 german translation contributor chapter 02

- contributor/de/03-contributor-ethos-article-de.asciidoc
Hi, with this chapter I had some difficulties doing a strict literal translation. So I took a little bit more freedom, at least for me that fits better. Please have a look what you are thinking about, I am looking forward to see your comments.
> #254 german translation contributor chapter 03

- introduction/es/03-how-works.asciidoc
Translation of [How does InnerSource work?](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/03-how-works.asciidoc)
> Add Spanish translation to intro -> how IS works

- contributor/it/03-contributor-ethos-article-it.asciidoc
- contributor/it/04-mechanics-of-contributing-article-it.asciidoc
- contributor/it/index.md
- introduction/it/index.md
I have just added the new index.md files for the current sections translated in italian. Hope during the next few days to  work on more chapters
> #382 added italian index.md for contributor and introduction

- CONTRIBUTING.md
As discussed in #419 , I added an instruction to explain how to point to a translated landing page.
> CONTRIBUTING.md: Add an instruction to point translated landing page

- product-owner/ja/06-closing-and-contact-article-ja.asciidoc
This PR is a part of #407 . Also, this is the final PR for Japanese translations for the main articles in all segments. :)
> Translation-ja: Add product-owner/ja/06-closing-and-contact

- trusted-committer/es/01-introduction-es.asciidoc
- trusted-committer/es/02-ensuring-product-quality-es.asciidoc
- trusted-committer/es/03-keeping-the-community-healthy-es.asciidoc
- trusted-committer/es/04-uplevelling-community-members-es.asciidoc
- trusted-committer/es/05-lowering-the-barriers-to-entry-es.asciidoc
- trusted-committer/es/06-advocating-for-the-communitys-needs-es.asciidoc
- trusted-committer/es/07-becoming-a-trusted-committer-es.asciidoc
- trusted-committer/es/08-conclusion-es.asciidoc
- trusted-committer/es/index.md
Creating the spanish translation for the Trusted Committers section including index.md file
> Spanish translation for Trusted Committers section

- introduction/es/index.md
Created spanish translation for introduction's index.md file as requested in issue #382
> added spanish translation for introduction's index.md file

- scripts/get_contributors.js
Fixes #377. Tested locally and seems to work as expected.
> Include reviewers as contributors

- introduction/fr/01-introduction.asciidoc
- introduction/fr/02-problèmes-résolus.asciidoc
- introduction/fr/03-comment fonctionne.asciidoc
- introduction/fr/04-avantages.asciidoc
- introduction/fr/05-principles.asciidoc
- introduction/fr/06-conclusion.asciidoc
Link changes #434 cause conflicts on #427 . But I was not sure how could I resolve it on #427 .
Instead of making changes on #427,  I rebased #427 to the latest commit and create a new PR to resolve the conflicts.
> Format and links by SJVle (rebase)

- contributor/es/01-introduction-article-es.asciidoc
- contributor/es/index.md
Translated to Spanish the following Contributor articles:
- **index**
- **01_Introduction**
Related Issue #436
> Translated "Contributor" index and Article 01 to Spanish

- introduction/es/04-benefits.asciidoc
The opening question mark was missing.
> Correct typo

- workbook/index.md
Needed to render under Workbook tile.
> New index.md file for the workbook

- meetings/examples/notes-email.md
- meetings/roles.md
Updating to match what we actually do.
> Update Scribe documentation

- trusted-committer/01-introduction-fr.asciidoc
Just a sloppy translation as baseline for teasing true french speakers into applying serious corrections. See #460.
> Sloppy translation as baseline for issue 460

- introduction/08-is-innersource-right.md
* Based off of feedback in [Open source for "other collaborative projects"].(https://github.com/InnerSourceCommons/InnerSourceLearningPath/discussions/500)
* View the [rendered document](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/rrrutledge-patch-1/introduction/08-is-innersource-right.md).
> Clarify when to InnerSource vs. open source

- product/outline.md
As suggested earlier in Slack I used the outline template to get my first ideas for what a product development focused learning path segment should contain. Some of the content is based on existing patterns, some is based on in-person conversations. This is a very early very rough draft of a sketch of an outline. I do hope that based on what is there others with more experience than myself get an idea of the general direction I would like to take this and add other relevant points to it (disclaimer: I am not a product person myself, so it is very likely I miss aspects).
> Create outline for product focused learning segment

- introduction/de/06-conclusion-de.asciidoc
Fix for [Check and fix links in translations](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/497).
> Fix malformatted links in German translation

- CONTRIBUTING.md
- introduction/02-problems-solved-captions-en.vtt
- introduction/03-how-works-captions-en.vtt
- introduction/04-benefits-captions-en.vtt
- introduction/05-principles-captions-en.vtt
- Added VTT files for Intro videos 02, 03, 04, 05. (Videos 01 and 06 did not need positioning tags)
- Updated CONTRIBUTING file with new caption info and guide.
> 370-caption-positioning

- contributor/05-benefits-of-contribution-article.asciidoc
- introduction/07-faq.asciidoc
- introduction/08-is-innersource-right.asciidoc
Ported from https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/523/files.
> Spelling corrections

- README.md
See [the document](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/rrrutledge-patch-1/README.md#trusted-committers).
> Welcome Senthil and Laura as Trusted Committers!!

- README.md
> Link to LICENSE.txt

- _config.yml
- crier.md
- roles/crier.md
- roles/facilitator.md
- roles/scheduler.md
- roles/scribe.md
* Followed the instructions at https://github.com/InnerSourceCommons/working-group-roles.
* Check it out at https://innersourcecommons.github.io/InnerSourceLearningPath/.
> Create roles documentation site

- scripts/README.md
> Update site generation instructions

- .github/workflows/publish-to-website.yml
Update deployment script to pick up on added files (not just modified files).
> Publish Project Leader Section

- config/urls.yaml
Resolves https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/559
> Add InnerSource Mentality Video

- introduction/outline.asciidoc
> Adding a metaphor of hammers as tools used in silos
