README.md

This merge request intends to fix #29. It adds two short paragraphs explaining our use Github Projects.
**Detailed description:**
The MR does not force a 1:1 mapping between README and the Kanban cards:
- I think, it's important to leave the overview table in the README as it is, because it delivers exactly the information a potential volunteer is interested in. (What work is needed? What's the expected time invest?)
- I also think, it's not necessary to modify the granularity / perspective of the cards and columns: They nicely mimic how a an artifact (e.g. article) flows from development to review to finish.
- As a consequence, I added two paragraphs simply explaining to readers and potential volunteers how to interpret the Kanban board.

Improving logical link between README.md and Kanban board

---

meetings/examples/notes-email.md
meetings/roles.md

* [This document](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/meeting-roles/meetings/roles.md) describes everything that I am doing to run the meetings of the Inner Source Learning Path working group.
* The document partitions the activities involved in running a successful meeting into a set of loosely-coupled, highly cohesive roles.
* While I am happy to continue to fill all of these roles, I feel that as the working group matures it will make sense to share leadership with other members of the community via filling these meeting roles.

Document meeting roles

---

introduction/principles.md

Work in progress, wanted to get at least the rough version up before tomorrow's meeting.

WIP intro principles

---

introduction/principles.md

#44 had a few nice changes already in easy-to-apply commit suggestion format that cannot be merged anymore since the #44 is already merged. Thus bringing them up as a PR again. I also resolved the open conversations where the proposed content had already been integrated into master with the conversations remaining open.
Thus, upon merge of this PR all content from the former principles PR would be integrated and the road free for more work on the principles article. @breakbottle

Transplant the commit suggestions from #44 onto the principles article.

---

meetings/roles.md

Scheduler no longer needs to create a brand-new meeting invite.

Updating for recurring meeting invite

---

contributor/outline.md

We already have a paragraph on asking questions. I think it's important to remind contributors to not reach out to individual host team members but use public (as in company wide readable), project specific communication channels where both question and answer can be archived, searched and later retrieved by any future contributor that might have a similar question. Benefit: Load with answering questions goes down, every member of the host team has the chance to answer and add their details, repeating questions that should make it into the docs are more obvious.

Enable future contributors by asking questions

---

contributor/03-contributor-ethos.md

This follows the format of the introduction article, and the content suggestions from the outline.

Fixes #72 adding detail to the contributor ethos.

---

contributor/04-mechanics-of-contributing.md

This pull request contains a first version of the "The Mechanics of Contributing" article according to the outline document.
I've used a more interactive, reader focussed writing style this time.
Looking for feedback if it's too colloquial in style.

First version of the mechanics of contributing article, addresses #74

---

meetings/roles.md

We're not really using the #innersourcecommons channel anymore.

Update to share in #general channel

---

workbook/03-product-owner.asciidoc

This version still uses a slightly annoying header format, I'll change that later of if someone feels like it - feel welcome to replace the headers with  the = notation via commit suggestion.
We probably should align our markup with the O'Reilly semantics, took it from the more general notation here: https://powerman.name/doc/asciidoc

Transfers the product owner workbook section to GitHub. Adresses #123.

---

workbook/01-introduction.asciidoc

This pull request contains the Introduction section of the Learning Path Google Doc moved. 
- Currently in blank form, will be transformed to ASCIIdoc later. 
- However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.

Initial move of workbook introduction from Google Doc to GitHub.

---

workbook/02-trusted-committer.asciidoc

This pull request contains the Trusted Committer section of the Learning Path Google Doc moved. 
- Currently in blank form, will be transformed to ASCIIdoc later. 
- However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.

Initial move of TC workbook from GoogleDoc to GitHub

---

.github/workflows/SyncToAtlas.yml

This GitHub Actions pipeline synchronizes our repo content on changes to master to the O'Reilly Atlas repository and merges in the local specifics to enable rendering the content properly.
As a last step a build on O'Reilly is triggered using the Gem described here: http://docs.atlas.oreilly.com/api.html
Secrets live in the project and run off of my account first. Having a bot account for that purpose probably would do no harm though.
Once this works, extending it to the other repos is a quick fix.
**TODO:** I might need to add runs using the actual `GITHUB_SHA` of the current state to enable using this as a pull request check. Or might need to add a second pipeline running against pull request checks separating the sync run on pushes to master and the pull request check run.

Atlas sync

---

workbook/04-contributor.asciidoc

This moves the no-open-comments version of the contributor section of the workbook to GitHub for further processing.

Moves the workbook contributor section to GitHub.

---

.github/workflows/SyncToAtlas.yml

This extends our GitHub-to-Atlas sync for syncing `master` to also sync the other, newly created repositories for the workbook and the other sections.

Extend Atlas Syncing to sync to the other 4 repos for the other products

---

.github/workflows/SyncToAtlas.yml

Currently the build results (PDF + EPub) build on every successful commit to master are not to easy to attribute to their individual products. 
This adds a few `echo` lines to the build script to change that...

Easier identification of build results from Atlas

---

contributor/05-benefits-of-contribution-article.asciidoc
trusted-committer/01-introduction.asciidoc

This PR is for the introduction article only.
Changed TC back to Trusted Committer; re-added the links. Kept their style suggestions.

Atlas TC edits merge back to github - 01 intro

---

meetings/roles.md

We just have a single conference call for the whole series now.

Remove tip about creating a conference call

---

config/urls.yaml

Hi, 
I updated the YT urls to the new non-O'Reilly-URLs in the `urls.yaml`, all thumbnails are confirmed by people pictured, see issue #214 
From what I see this is independent of setting publishing times on the videos, currently both kind of videos are unlisted (the old ones with O'Reilly Branding and the new ones without), which means: 
- Anyone with the video link can see this Video --> links will now lead to the non-O'Reilly videos
- This video won't appear on your channel page. It also won't appear in YouTube search results unless someone adds it to a public playlist.
I will set the publishing times of the playlists separately

update the YT urls to the new non-O'Reilly-URLs

---

CONTRIBUTING.md

I would like to propose to use two-character language code prefix in the file name for translations as follows.
Original: 01-introduction.asciidoc
German translation: de/01-introduction-de.asciidoc
If we use two-character language code in the filename, that makes easier to recognize for other language speaking person when they try to find the files. Also easier to make a regular expression to manipulate it.
$ find . -name '01-intro*' -print
./ja/01-introduction-ja.asciidoc
./de/01-introduction.asciidoc
./01-introduction.asciidoc
The other reason is, using multibyte characters in filename makes difficult to use the filenames from a command line.

CONTRIBUTING.md: Update Translation Instruction

---

.gitignore
product-owner/01-opening-article.asciidoc
product-owner/02-how-difficult-it-is-to-be-a-middle-manager-article.asciidoc
product-owner/03-major-benefits-are-built-into-the-innersource-process-article.asciidoc
product-owner/04-new-roles-and-responsibilities-article.asciidoc
product-owner/05-recap-takeaways-article.asciidoc
product-owner/06-closing-and-contact-article.asciidoc
scripts/README.md
scripts/generate_learning_path_markdown.js

Adds a script for generating markdown files required for hosting Learning Path on innersourcecommons.org.
Only supports English articles initially - intent is to extend for non-English as part of #249.

Generate learning path markdown

---

trusted-committer/de/02-ensuring-product-quality-de.asciidoc
trusted-committer/de/03-keeping-the-community-healthy-de.asciidoc

I finished Translation for chapter 02 and 03 of trusted committer section, compare #256

translation for trusted committer chapter 02 and 03 to german added

---

introduction/03-how-works.asciidoc
introduction/de/03-how-works-de.asciidoc
introduction/ja/03-how-works-ja.asciidoc
introduction/zh/03-how-works-zh.asciidoc

The trusted committer pattern link is changed, we need to update the link in the learning path.

Fixed the broken link of trusted committer

---

contributor/03-contributor-ethos-article.asciidoc
contributor/it/03-contributor-ethos-article-it.asciidoc
contributor/ja/03-contributor-ethos-article-ja.asciidoc
contributor/outline.asciidoc
contributor/zh/03-contributor-ethos-zh.asciidoc
introduction/03-how-works.asciidoc
introduction/de/03-how-works-de.asciidoc
introduction/it/03-how-works.asciidoc
introduction/ja/03-how-works-ja.asciidoc
introduction/ru/03-how-works.asciidoc
introduction/zh/03-how-works-zh.asciidoc
workbook/04-contributor.asciidoc

Rather than pointing to patterns in the InnerSourcePatterns GitHub repo, point to the online book at https://patterns.innersourcecommons.org
Implements #373

Switch links to patterns book

---

product-owner/06-closing-and-contact-article.asciidoc

In the following YouTube video, Silona mentions the Trusted Committer instead of the trusted committee. This wording effect the translation article.
https://www.youtube.com/watch?v=0beNc9V-tro&t=20s
I also added a link to Trusted Committer.

Product Owner: Minor fix in closing message

---

product-owner/ja/01-opening-article-ja.asciidoc
trusted-committer/ja/04-uplevelling-community-members-ja.asciidoc
trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
trusted-committer/ja/06-advocating-for-the-communitys-needs-ja.asciidoc
trusted-committer/ja/07-becoming-a-trusted-committer-ja.asciidoc

Recent Japanese translation files have broken links for new site format of InnerSource Commons. This PR fixes them.

Translation-ja: Fix broken links in Japanese translation

---

introduction/fr/01-introduction.asciidoc
introduction/fr/02-problèmes-résolus.asciidoc
introduction/fr/03-comment fonctionne.asciidoc
introduction/fr/04-avantages.asciidoc
introduction/fr/05-principles.asciidoc
introduction/fr/06-conclusion.asciidoc
introduction/fr/index.md

This pull request adds a machine translated version of the introduction section, including the index.ml to French using the DeepL machine translator.
Let's review this for quality if machine translation to french is feasible. Also, we might want to take a look if we can take the free translation service for this or would need to give any attribution to it etc - as well as to the human reviewers obviously.
This addresses #397

Adds a machine translation of the introduction articles and index.md to French using DeepL

---

config/urls.yaml

Updating the Youtube Link for the Contributor content with the new youtube link of the modified video.
Related to https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/122

Updating youtube link

---

.github/workflows/publish-to-website.yml
config/urls.yaml

Along with https://github.com/InnerSourceCommons/innersourcecommons.org/pull/130, this fixes #349.
This new GitHub Action will (if relevant files have changed on master):
- Checkout LearningPath and innersourcecommons.org repos
- Checkout or create a `publish-latest-learning-path` branch of innersourcecommons.org
- Run the scripts to generate website markdown from learning path articles and data
- Commit and push to the `publish-latest-learning-path` branch of innersourcecommons.org
Opening a Pull Request will be done a separate action run on innersourcecommons.org repo, due to limitations of GitHub deploy keys (see https://github.com/InnerSourceCommons/innersourcecommons.org/pull/130).
This has been tested against earlier commits, where the action was configured to build from this branch …

Learning path automation

---

contributor/01-introduction-article.asciidoc
contributor/de/01-introduction-article-de.asciidoc
contributor/it/01-introduction-article-it.asciidoc
contributor/zh/01-introduction-zh.asciidoc

This PR fixes a bug that was introduced in #434 .
In the changed sentence, the link should point to introduction article in trusted committer segment. Because the sentence mentioned a video which is available in the article.
The same change included in #443 for Japanese article.

Changed links to point to proper content

---

workbook/04-contributor.asciidoc

Fixes https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/122

Clarify Contributor workbook question

---

CONTRIBUTING.md

Add machine translation instructions

---

config/urls.yaml
contributor/05-benefits-of-contribution-script.asciidoc
introduction/02-problems-solved.asciidoc
introduction/03-how-works.asciidoc
introduction/04-benefits.asciidoc
introduction/05-principles.asciidoc
introduction/07-faq.asciidoc
introduction/fr/03-how-works-fr.asciidoc
introduction/fr/06-conclusion-fr.asciidoc
introduction/it/01-introduction-it.asciidoc
scripts/generate_learning_path_markdown.js

I apologize that my anal nature got the better of me. Nearly all of the files apart from `generate_learning_path_markdown.js` contain capitalization fixes.
As for `generate_learning_path_markdown.js`, I ended up adding a couple of small functions that
- don't assume the article has corresponding video URL entries in the URL config (this was the main bug)
- article title parsing looks for both `.asciidoc` and `.md` syntaxes
There are now enough article-related functions in this file that I'm open to moving them into their own module. It could be overkill though, since all uses are still contained in this script.
I also wonder whether the hard-coded YouTube thumbnail URL (see `getYouTubeImage()`) should be moved to the front-end template instead of here? 
And as always, appreciate any …

488 publish articles without videos

---

package-lock.json
scripts/generate_learning_path_markdown.js
scripts/get_contributors.js
scripts/package-lock.json
scripts/package.json

This PR introduces the throttling plugin to our GraphQL calls. It prevents the [rate-limiting errors](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/503) we were seeing prior to this, but at the cost of increased time. It now takes a couple of minutes for `scripts/generate_learning_path_markdown.js` to complete.
The throttling plugin requires two new functions to be defined: `onRateLimit()` and `onSecondaryRateLimit()`, neither of which should get triggered if the throttling is working as intended. I didn't do anything different from the documentation in those. 
I also made small changes to the auth and query objects. The [@octokit README](https://github.com/octokit/graphql.js#variables) specifically mentions string template literals as an anti-pattern, so I removed …

503 throttle graphql requests

---

.github/workflows/publish-to-website.yml
scripts/README.md

To support i18n at innersourcecommons.org, LearningPath also needs to be partially changed.
This change should or should not be merged depending on the success or failure of the following changes
@rrrutledge, could you check the following PR?
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/412

Change of publishing path due to i18n support for innersourcecommons.org page

---

scripts/generate_learning_path_markdown.js
scripts/section_data.json
workbook/workbook-image-template.html

It's all new! and improved! haha
This PR includes an HTML image template, new static images, and a small change to section data JSON to get them included during site generation.
Please let me know your feedbacks! TY!
(This PR is tangentially related to a previously closed PR: https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/522)

375-static-workbook-images

---

scripts/generate_learning_path_markdown.js
scripts/get_article_files.js

This PR does two things:
1. Fixes a bug where the new VTT caption files were being considered articles, causing the site generation script to x_x.
2. Any articles without YouTube videos will now reference a default image.
Related to Issue #528 
The actual image is included in a sister PR in the innersourcecommons.org repository: https://github.com/InnerSourceCommons/innersourcecommons.org/pull/468

528-article-default-image

---

product/01-introduction.md
product/02-innersource-and-agile.md
product/05-shared-ownership.md
product/06-relation-to-open-source.md

* Thank you for this work, @MaineC!
* Fixed some typos.
* @MaineC what future changes do you have planned?
* I think that, in-general, these articles could be split up so that each is more targeted.
With more targeted segments we may find there's enough overlap to merge some articles here into existing Learning Path segments or patterns and just link to them.
* We should decide on what checkpoint/level would we like for this work to make it to [the website](https://innersourcecommons.org/learn/learning-path/).

Review Product People Section

---

scripts/get_contributors.js

* For some reason, some author objects in the graph API are missing a user object (and subsequently a user URL).
* Users without a URL don't get a link to their GitHub profile.
* Fix is to explicitly ensure that we don't overwrite a good user URL with an empty one.
* See https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/536

Fix user tile bug

---

introduction/09-innersource-mentality.asciidoc

* Look at the [accompanying video](https://youtu.be/rDqH3JIvbMc). 
* See the accompanying [Slack conversation](https://innersourcecommons.slack.com/archives/C04DT6NQX7G/p1682368268608199)

The InnerSource Mentality segment

---

scripts/get_contributors.js

* Filter bot users out of contributors list.
* You can see the bot user missing from the list of contributors on the (local) left article with these changes, whereas it is present on the right that does not have these changes.  https://innersourcecommons.org/it/learn/learning-path/trusted-committer/01/
* Resolves https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/556.

Bot user should not show as contributor

---

.github/workflows/publish-to-website.yml

When builds are triggered within about 4 min of each other, the parallel calls to GitHub's GraphQL API clobber one another. Even with a throttling helper, the clobbering results in a too-many-requests API error, and the build fails.
This small change should hopefully prevent this error in the future. It will check if the build/workflow is already running, and if so, cancels it. If there are multiple builds in quick succession, only the latest one will publish.

Added concurrency section to Publish Website workflow (Issue 575)

---

assets/thumbnails/thumbnail_rationale.asciidoc
scripts/README.md

Steps I followed for the `Project Leader` section.

How to create a new Learning Path section
